language: java
before_install:
- git clone https://github.com/informatici/openhospital-core.git
- cd openhospita-core
- mvm clean install
- sudo service mysql stop
- docker-compose up -d
- docker ps
after_success:
- docker-compose down
